### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by takuto95** [takuto95/old-protospace-31488#1]
ProtoSpaceの挙動の確認をお願いします。
■URL 
https://protospace-31488.herokuapp.com/

■確認ポイント
●ユーザ管理機能
1.必要な情報を入力すると、ユーザー新規登録ができる
2.必要な情報を入力すると、ログインができる
3.誤った情報では、そのページに留まる
4.未ログイン時には、ヘッダーに「新規登録」「ログイン」のリンクが
存在する
5.ログイン時には、ヘッダーに「ログアウト」「New Proto」のリンクが
存在する
6.ログイン時には、トップページに「こんにちは、〇〇さん」と
ユーザー名が表示されている
7.トップページから、ログアウトができる
●プロトタイプ投稿機能
8.必要な情報を入力すると、プロトタイプが投稿でき、
トップページに遷移する
9.誤った情報では、そのページに留まる
10.投稿した情報は、トップページに表示される
●プロトタイプ詳細ページ機能
11.トップページのプロトタイプをクリックすると、詳細ページへ遷移する
12.詳細ページには見本と同様にプロトタイプの情報が表示されている
13.投稿したユーザーだけに「編集」「削除」のリンクが存在する
●プロトタイプ編集機能
14.詳細ページのリンクをクリックすると、編集ページへ遷移する
15.必要な情報を入力すると、プロトタイプが編集でき、詳細ページへ遷移する
16.誤った情報では、その編集ページに留まる
●プロトタイプ削除機能
17.詳細ページリンクをクリックすると、プロトタイプが削除できる
18.削除が完了すると、トップページへ遷移する
●コメント投稿機能
19.詳細ページでコメントを投稿すると、詳細ページに戻ってくる
20.詳細ページには投稿したコメントとその投稿者が表示されている
21.空のコメントでは保存されない
22.コメント投稿欄はログインしているユーザーのみに表示されている
●ユーザー詳細ページ機能
23.各ページのユーザー名をクリックすると、
ユーザーの詳細ページへ遷移する
24.ユーザーの詳細ページには、そのユーザーの詳細情報と、
そのユーザーが投稿したプロトタイプが表示されている
●その他
25.未ログイン時は、特定のページ以外には遷移できず、
ログインページにリダイレクトされる
26.他のユーザーが投稿したプロトタイプの編集ページにURLを直接入力して遷移しようとすると、トップページにリダイレクトされる

**Comment by kana-create** [comment]
風岡さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・詳細ページには見本と同様にプロトタイプの画像が表示されません（投稿ユーザーでない人が詳細ページを見る時）
・編集時、誤った情報で編集しようとすると「We're sorry, but something went wrong.」が表示されます。
・プロトタイプが編集時、編集して投稿すると詳細ページへ遷移できない「We're sorry, but something went wrong.」が表示されます。（おそらく画像が空になっているかと推測されます）

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by takuto95** [comment]
kana-createさん
レビューありがとうございます。

＞・詳細ページには見本と同様にプロトタイプの画像が表示されません（投稿ユーザーでない人が詳細ページを見る時）
⇨画像のリンクが切れた状態になる認識で合っていますか？
　私的には、herokuのFreeプランの仕様で一定時間時間がたったので、削除されていると考えています。
　(現に画像アップロード時に指摘事項と同様の確認を行いましたが、問題ありませんでした。)

＞・編集時、誤った情報で編集しようとすると「We're sorry, but something went wrong.」が表示されます。
⇨確認し、修正します。

＞・プロトタイプが編集時、編集して投稿すると詳細ページへ遷移できない「We're sorry, but something went wrong.」が
表示されます。（おそらく画像が空になっているかと推測されます）
⇨確認し、修正します。

**Comment by kana-create** [comment]
風岡さん、ご提出ありがとうございます！
また修正も有難うございました！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
画像の表示についてはご指摘の通りリンク切れを確認しました。

[修正箇所]
・ユーザー詳細機能：各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移できません。自分のページへ遷移します。
以下は必須実装ではありませんが、修正した方が良いと思います。
・コメント投稿機能：空で投稿した際に既に投稿されているコメントが消えてしまいます。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by takuto95** [comment]
再レビューありがとうございます。

[修正箇所]
・ユーザー詳細機能：各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移できません。自分のページへ遷移します。
⇨修正しました。

以下は必須実装ではありませんが、修正した方が良いと思います。
・コメント投稿機能：空で投稿した際に既に投稿されているコメントが消えてしまいます。
⇨修正しました。

**Comment by kana-create** [comment]
風岡さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください！

**Comment by takuto95** [comment]
ご確認ありがとうございます。
本コメントをもちまして、クローズします。
